<?php
$section = $args['section']; $rows = $args['rows']; $mode = $args['mode']; $groups = array();
foreach ( $rows as $row ) $groups[ $row['group'] ?: __( 'Overview', 'aibridze' ) ][] = $row;
?>
<section class="service-shell service-shell--<?php echo esc_attr( $args['theme'] ); ?> service-section service-section--<?php echo esc_attr( $mode ); ?>" data-service-section><div class="container">
	<header class="service-section__header"><?php if ( aibridze_service_value( $section . '_eyebrow' ) ) : ?><p class="service-kicker section-callout"><?php echo esc_html( aibridze_service_value( $section . '_eyebrow' ) ); ?></p><?php endif; ?><?php if ( aibridze_service_value( $section . '_title' ) ) : ?><h2><?php echo esc_html( aibridze_service_value( $section . '_title' ) ); ?></h2><?php endif; ?><?php echo wp_kses_post( wpautop( aibridze_service_value( $section . '_description' ) ) ); ?></header>
	<?php if ( in_array( $mode, array( 'tabs', 'technology' ), true ) ) : ?><div class="service-tabs" role="tablist"><?php foreach ( array_keys( $groups ) as $index => $group ) : ?><button type="button" class="service-tab<?php echo 0 === $index ? ' is-active' : ''; ?>" data-service-tab="<?php echo esc_attr( sanitize_title( $group ) ); ?>"><?php echo esc_html( $group ); ?></button><?php endforeach; ?></div><?php endif; ?>
	<div class="service-items service-items--<?php echo esc_attr( $mode ); ?>"><?php foreach ( $groups as $group => $items ) : ?><div class="service-group<?php echo in_array( $mode, array( 'tabs', 'technology' ), true ) && $group !== array_key_first( $groups ) ? ' is-hidden' : ''; ?>" data-service-panel="<?php echo esc_attr( sanitize_title( $group ) ); ?>"><div class="service-group__grid">
	<?php foreach ( $items as $index => $row ) : ?><article class="service-card"<?php echo 'cards' === $mode ? ' tabindex="0"' : ''; ?>><div class="service-card__body"><?php if ( $row['image'] ) : ?><img class="service-card__icon" src="<?php echo esc_url( $row['image'] ); ?>" alt="" loading="lazy"><?php endif; ?><span class="service-card__number"><?php echo esc_html( str_pad( (string) ( $index + 1 ), 2, '0', STR_PAD_LEFT ) ); ?></span><h3><?php echo esc_html( $row['title'] ); ?></h3><div><?php echo wp_kses_post( wpautop( $row['description'] ) ); ?></div><?php if ( $row['link_label'] ) : ?><a href="<?php echo esc_url( $row['link_url'] ?: '#' ); ?>"><?php echo esc_html( $row['link_label'] ); ?> →</a><?php endif; ?></div></article><?php endforeach; ?>
	</div></div><?php endforeach; ?></div>
	<?php if ( 'cards' === $mode ) : ?><div class="service-slider-controls" aria-label="<?php esc_attr_e( 'Card navigation', 'aibridze' ); ?>"><button type="button" data-service-slide="prev" aria-label="<?php esc_attr_e( 'Previous card', 'aibridze' ); ?>">‹</button><button type="button" data-service-slide="next" aria-label="<?php esc_attr_e( 'Next card', 'aibridze' ); ?>">›</button></div><?php endif; ?>
</div></section>
