<?php $title = aibridze_service_value( 'intro_title' ); if ( ! $title ) return; $image = aibridze_service_value( 'intro_image' ); $layout = get_post_meta( get_the_ID(), '_aibridze_service_layout', true ); ?>
<?php if ( 'rag' === $layout ) : ?>
<section class="service-intro service-intro--rag service-shell service-shell--dark"><div class="container"><div class="service-intro--rag__top"><div><?php if ( aibridze_service_value( 'intro_eyebrow' ) ) : ?><p class="service-kicker section-callout"><?php echo esc_html( aibridze_service_value( 'intro_eyebrow' ) ); ?></p><?php endif; ?><h2><?php echo esc_html( $title ); ?></h2><div class="service-richtext"><?php echo wp_kses_post( wpautop( aibridze_service_value( 'intro_description' ) ) ); ?></div></div><?php if ( $image ) : ?><figure><img src="<?php echo esc_url( $image ); ?>" alt="" loading="lazy"></figure><?php endif; ?></div></div></section>
<?php return; endif; ?>
<?php if ( 'voice' === $layout ) : ?>
<section class="service-intro service-intro--voice service-shell service-shell--dark"><div class="container"><div class="service-intro--voice__top"><div><?php if ( aibridze_service_value( 'intro_eyebrow' ) ) : ?><p class="service-kicker section-callout"><?php echo esc_html( aibridze_service_value( 'intro_eyebrow' ) ); ?></p><?php endif; ?><h2><?php echo esc_html( $title ); ?></h2><div class="service-richtext"><?php echo wp_kses_post( wpautop( aibridze_service_value( 'intro_description' ) ) ); ?></div></div><?php if ( $image ) : ?><figure><img src="<?php echo esc_url( $image ); ?>" alt="" loading="lazy"></figure><?php endif; ?></div></div></section>
<?php return; endif; ?>
<?php if ( 'vision' === $layout ) : ?>
<section class="service-intro service-intro--vision service-shell service-shell--dark"><div class="container"><div class="service-intro--vision__top"><div><?php if ( aibridze_service_value( 'intro_eyebrow' ) ) : ?><p class="service-kicker section-callout"><?php echo esc_html( aibridze_service_value( 'intro_eyebrow' ) ); ?></p><?php endif; ?><h2><?php echo esc_html( $title ); ?></h2><div class="service-richtext"><?php echo wp_kses_post( wpautop( aibridze_service_value( 'intro_description' ) ) ); ?></div><h3><?php esc_html_e( 'How Computer Vision Works', 'aibridze' ); ?></h3></div><?php if ( $image ) : ?><figure><img src="<?php echo esc_url( $image ); ?>" alt="Person experiencing a computer vision interface" loading="lazy"></figure><?php endif; ?></div><div class="vision-how"><article><strong>1. Capture &amp; Process</strong><span>The system captures images or video and processes visual data to prepare it for AI analysis.</span></article><article><strong>2. Detect &amp; Understand</strong><span>AI models identify objects, patterns, text, faces, movements, or other relevant visual information.</span></article><article><strong>3. Analyze &amp; Act</strong><span>The system converts visual insights into predictions, decisions, or automated actions.</span></article></div><blockquote>From pixels to actionable intelligence, computer vision helps businesses understand what is happening in the visual world.</blockquote></div></section>
<?php return; endif; ?>
<section class="service-intro service-shell service-shell--dark"><div class="container service-intro__grid"><div><?php if ( aibridze_service_value( 'intro_eyebrow' ) ) : ?><p class="service-kicker section-callout"><?php echo esc_html( aibridze_service_value( 'intro_eyebrow' ) ); ?></p><?php endif; ?><h2><?php echo esc_html( $title ); ?></h2><div class="service-richtext"><?php echo wp_kses_post( wpautop( aibridze_service_value( 'intro_description' ) ) ); ?><?php if ( get_the_content() ) the_content(); ?></div></div><?php if ( $image ) : ?><figure><img src="<?php echo esc_url( $image ); ?>" alt="" loading="lazy"></figure><?php endif; ?></div></section>
